### ISSUE TITLE
CRS Indefinido?

### ISSUE THREAD

**Issue by felixlapalma** [bitsandbricks/atlas_espacios_verdes#1]
Buenas, 

Al revisar los shapes en [atlas](https://github.com/bitsandbricks/atlas_espacios_verdes/tree/master/data/processed/osm), se observa que no poseen un CRS definido.

```
> geopandas.read_file('atlas').crs
<Projected CRS: PROJCS["unknown",GEOGCS["GCS_unknown",DATUM["D_Unk ...>
Name: unknown
Axis Info [cartesian]:
- [east]: Easting (metre)
- [north]: Northing (metre)
Area of Use:
- undefined
Coordinate Operation:
- name: unnamed
- method: Lambert Azimuthal Equal Area
Datum: D_Unknown_based_on_WGS84_ellipsoid
- Ellipsoid: WGS 84
- Prime Meridian: Greenwich
```

Se podra actualizar con el CRS correspondiente ?

**Comment by bitsandbricks** [comment]
Buenas Felix!

El shapefile usa una de las [proyecciones que utiliza el IGN para representar la Argentina](https://www.ign.gob.ar/NuestrasActividades/ProduccionCartografica/sistemas-de-proyeccion). Es la Lambert Equiareal (de las 3 que usa IGN, la que permite caclular áreas con mejor precisión) con punto de tangencia  40°S 60°O.    

El CRS está definido en el shapefile, con `crs = "+proj=laea +lat_0=-40 +lon_0=-60 +x_0=0 +y_0=0 +ellps=WGS84 +units=m +no_defs"`. 

Si lo abrís deberían aparecer todos los polígonos correctamente proyectados, y lo podés transformar a cualquier otra proyección.

Lo que no tiene el CRS es código/nombre propio (estilo 4326/WGS84), creo que por eso geopandas lo declara "unknown", pero no debería afectar en nada su uso.

**Comment by felixlapalma** [comment]
Buenas!

Eso me di cuenta despues de levantar el issue :-P
Gracias por la aclaracion y el detalle en la respuesta!
